---
- name: processing_meraki_alerts
  hosts: localhost
  module_defaults:
    ansible.builtin.uri:
      validate_certs: false

  collections:
    - community.general.cisco_webex

  vars:
    aTypeId: "{{ payload.alertTypeId }}"



  tasks:
    - name: WebexTeams_Alert_Notification_RogueDHCP
      community.general.cisco_webex:
          recipient_type: roomId
          recipient_id: "{{ roomid }}"
          msg_type: markdown
          personal_token: "{{ webex_api }}"
          msg: "<h4>Network: {{ payload.networkName }}</h4> reported the following alert condition **{{ payload.alertTypeId }}** 
          and added <h4>mac address:</h4> {{ payload.alertData.eth }} to the blocked servers list  \n
          <h4>Error_Info: https://documentation.meraki.com/MX/DHCP/Tracking_Down_Rogue_DHCP_Servers</h4>"
      when: aTypeId == "rogue_dhcp"
      ignore_errors: yes


    - name: WebexTeams_Alert_Notification-cableError
      community.general.cisco_webex:
        recipient_type: roomId
        recipient_id: "{{ roomid }}"
        msg_type: markdown
        personal_token: "{{ webex_api }}"
        msg: "**Network: {{ payload.networkName }}** reported the following alert condition **{{ payload.alertTypeId  }}** for 
        <h4>
        Device: {{ payload.deviceName }}  \n
        Serial: {{ payload.deviceSerial }}  \n
        Port: {{ payload.alertData.portNum }}  \n
        Previous_Value: {{ payload.alertData.prevStatus }}  \n
        Current_Value: {{ payload.alertData.status }}  \n
        Description: {{ payload.alertData.portDesc }}  \n
        Error_Info: https://documentation.meraki.com/MS/Monitoring_and_Reporting/Using_the_Cable_Test_Live_tool  \n
        </h4>  \n
        Cable Test sent, standby for results"
      when: aTypeId == "port_cable_error"
      ignore_errors: yes
